### ISSUE TITLE
Can't catch exceptions if camera is in use

### ISSUE THREAD

**Issue by aaronpowell** [Azure/Communication#109]
I've come across a problem that if you try and create a `LocalVideoStream` from a camera that is in use (say, you have a virtual camera running but you select the physical camera) an exception is thrown telling you that the device is in use.
 
The exception makes sense, but I can't seem to catch the error. It manifests itself as a promise failing, but the `LocalVideoStream.switchSource`'s `catch` method doesn't get triggered, nor does a `try`/`catch` wrapper work. I also tried adding a handler to `window.onunhandledrejection` but that didn't seem to trigger.

Having a way to gracefully handle an exception will make it easier to recover in-app.

**Comment by aaronpowell** [comment]
This is somewhat related to #99

**Comment by akania** [comment]
Thank you @aaronpowell for feedback, we'll fix it in future release.

**Comment by eliaspuurunen** [comment]
We've experienced this too. In our case, if the camera is in use and you select another camera, the SDK doesn't actually display the newly selected camera. We have to refresh the page and select the not-in-use camera. Happening on Chrome, Windows 10.

**Comment by lswider** [comment]
@akania any idea when this will be fixed?

**Comment by cwhil2492** [comment]
Hi @aaronpowell and @eliaspuurunen, If your camera is being used by a different process other than the chrome browser, then when initiating a call, call will start with video off and a cameraStartFailed: true call diagnostic will be raised. You can listen or this call diagnostic being raised so that you can then forexample take action such as displaying a toast in the UI to say that the video failed to start. You will also see a sourceUnavailableError in the log.

If your video is off, and you try to start your video on during a call (call.starVideo api), the call.startVideo api will throw a sourceUnavailable error.

You should see our documentation updated with all this information by tomorrow. Call Diagnostics information is already there: https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/calling-client-samples?pivots=platform-web#call-diagnostics
