### ISSUE TITLE
Web: Remote user display name not available on first call answer

### ISSUE THREAD

**Issue by eliaspuurunen** [Azure/Communication#119]
**Describe the bug**
When a user answers an incoming call, their display name (as set by callAgent.updateDisplayName) is not sent to the remote party.

**To Reproduce**
1. Have a user start a group call.
2. Invite another user to the group call.
3. Set display name via callAgent.updateDisplayName on remote user
4. Accept the group call on the remote user.

**Expected behavior**
UpdateDisplayName should set the display name that must be transmitted to remote participants.

**Comment by mariusu-msft** [comment]
Hi,

@eliaspuurunen thanks for your report. We are working on fixing this and providing a better interface for displayName.

It should be available in the next release. DisplayName will be immutable for a CallAgent session. cc: @ashishvirani7 

Keeping this open until new functionality is available.

Meanwhile for your issue I believe there’s a workaround available. @akania can you help?

Thanks,
Marius

**Comment by rdweaver** [comment]
I'm running into this issue as well. When is the next release? Any updates? @mariusu-msft @ashishvirani7 @akania

**Comment by mariusu-msft** [comment]
@rdweaver today for JS SDK and in next couple of days for iOS and Android

**Comment by btmpn** [comment]
Hello, I was also affected by the problem. Since the update/release for JS SDK the displayName is available when the call in a connected state.

But there's another issue or question to this topic:

The remoteParticipants array in the call object is empty for a incoming call before it is accepted / connected. So there's no possibility to see who is calling right now?

I know that there is the callerIdentity property available in the call object but this does only contain the communicationUserId without any displayName. It would be great if there would be a possibility to see at least the displayName of the caller, it would be even better if the remoteParticipants array would also be delivered with values, which contain all participants with their display names.

Thanks!

**Comment by akania** [comment]
@btmpn currently to learn who is the caller, once you receive an incoming call ( subscribe to callAgent 'callsUpdated' event and check for incoming calls ) you have to subscribe to 'remoteParticipantsUpdated' event and check for 'added' participants, you'll thne be able to find a participant who is the caller ( based on the callerIdentifier ) and on that participant you have to subscribe to 'displayNameChanged' event to get his display name

we'll improve this flow in upcoming release

**Comment by btmpn** [comment]
Thanks @akania, I did not know that. I'll try this.

**Comment by ProbablePrime** [comment]
It looks like this should have been resolved with the releases we've had recently. Was this the case, Can we close this issue @akania ?

**Comment by RinaRish** [comment]
Closing, feel free to reopen
