### ISSUE TITLE
Subscribe to mute all option by organiser - calling sdk

### ISSUE THREAD

**Issue by Kalyan492** [Azure/Communication#197]
Is there any event to subscribe when meeting organiser uses mute all option? Currently I am using remoteParticipant "isMuteChanged" event. But when an organiser mutes all participants, I am not able to run isMuteChanged event. Is there a way to handle this?

**Comment by akania** [comment]
hi @Kalyan492 thank you for reporting, currently SDK doesn't expose information that local participant was muted by another participant,  this feature is on the roadmap and will be ready in q2.

**Comment by ProbablePrime** [comment]
@akania Do we have any updated timeline on when this would be available?

**Comment by akania** [comment]
@ProbablePrime sorry for slow reply, this was released on v1.0.0-beta.10 
 [release notes](https://github.com/Azure/Communication/blob/master/releasenotes/acs-javascript-calling-library-release-notes.md)

**Section about isMuted**
**isMicrophoneMuted changed to isMuted, if isMuted is set to true it indicates that local user is muted because of**

- application called mute() method on the Call object and it resolved
- in Teams interop scenarios - Teams user muted ACS user
- in Teams interop scenarios - Teams user triggered 'mute all' feature for all participants in the meeting


3.1 isMutedChanged event was introduced on the Call object


closing
