### ISSUE TITLE
Does it support React Native?

### ISSUE THREAD

**Issue by webmagic123** [Azure/Communication#199]
Hi @sabrimev @likern

did you manage to make it work with react-native?

related issue - https://github.com/Azure/Communication/issues/45

**Comment by ddematheu2** [comment]
We currently don't have bindings for React Native. Could you share specifics of the scenario you are trying to enable with React Native with ACS?

**Comment by likern** [comment]
I haven't yet tried, I'm working on another kind of application.

This application is expected to have feature "person to person" or "group communication", similar to chats. Might be added after first public release.
Right now doesn't work on that.

But in general, React Native is a natural fit to develop cross-platform chat applications or applications with integrated chat functionality.
Because it's supported by Microsoft on Windows and MacOS, and working on Android / iOS.
Nowadays it's expected that chat-like apps would be available on any major platform. Hence my interest in React Native support.

**Comment by kvntzn** [comment]
Same concerns too.

 Right now is it possible to integrate ACS in a react native ? 
 And also are there any plans in the future to do a react-native version ?

**Comment by ddematheu2** [comment]
It is possible. We currently have a very small PoC of it internally. If it would be helpful as a starting point, we could look to post it out and gather feedback.

**Comment by xTEddie** [comment]
FYI, I was able to leverage ACS Android/iOS SDK to build a npm package for react-native. It's still a work in progress.

I used [react-native-builder-bob](https://github.com/callstack/react-native-builder-bob) to set up the base of the library for react-native. I was able to create  `LocalVideoView` & `RemoteVideoView` components to render the video streams. I was able to expose a `NativeModule` to handle the calls such as accept video, stop video, flip camera, mute/unmute, turn on/off local video, use speaker, etc. 

In the Native layer, I had to use singletons to handle the local video & remote video streams as well as for `CallClient` & `CallAgent` since they are required to be accessed in multiple files. 

Some issues I've faced was the package does not work on the more recent versions of react-native. The latest version that I tried and worked is `v0.62.0-rc.1`

References:
https://reactnative.dev/docs/native-modules-intro
https://reactnative.dev/docs/native-components-android
https://reactnative.dev/docs/native-components-ios

**Comment by ddematheu2** [comment]
@anjulgarg for vis.

**Comment by jahead** [comment]
@ddematheu2 yes it would be of interest for us too, we are looking at the option to move from twilio, which has a community driven react native solution that works much like the what was described above.

The react native library above should just be a consumer of the IOS /Java SDK. No need to reinvent the wheel

**Comment by sowsan** [comment]
It would be great to have an official react-native SDK for ACS. Like Agora: https://docs.agora.io/en/Video/landing-page

**Comment by sabrimev** [comment]
@webmagic123 I had concerns and used something else.

**Comment by hmheng** [comment]
I agree thaf this would be truly important to have first class SDK of ACS for React Native.

**Comment by ProbablePrime** [comment]
#AB2236945

**Comment by asmailov** [comment]
Hi. 
I've tried using [JS Chat packages](https://www.npmjs.com/package/@azure/communication-chat) in the **Expo** app.
After directly updating some modules (to use browser version instead of node) I've managed to run a chat client and chat thread client. I can:
- send a message
- retrieve participants
- retrieve messages

I am however stuck when trying to use real-time notifications. There is a package used in the `communication-signaling` by the name: `@skype/tstrouter` it's minified and not publicly available (couldn't find online public repository). I've tried to analyze it - it seems to have a very tight dependency on the browser API...
I assume there should be a possibility to extract a "core" and substitute with the React Native WebSocket implementation - it should be the main component of the "real-time" communication (at least I hope it is 😄). 
Currently, it looks like it would too time consuming to try to reverse engineer that minified code, unless we can get a source code for `@skype/tstrouter`.

**Comment by xTEddie** [comment]
@asmailov, I ran into this issue before. There was a [pull request](https://github.com/Azure/azure-sdk-for-js/pull/14992) to enable real-time notifications on React Native which recently got checked in. These changes were available starting on [@azure/communication-chat@1.0.1-alpha.20210428.2](https://www.npmjs.com/package/@azure/communication-chat/v/1.0.1-alpha.20210428.2). I tried it and it worked for me.

**Comment by asmailov** [comment]
> @asmailov, I ran into this issue before. There was a [pull request](https://github.com/Azure/azure-sdk-for-js/pull/14992) to enable real-time notifications on React Native which recently got checked in. These changes were available starting on [@azure/communication-chat@1.0.1-alpha.20210428.2](https://www.npmjs.com/package/@azure/communication-chat/v/1.0.1-alpha.20210428.2). I tried it and it worked for me.
> 
> That's for chat only and not calling.

It doesn't work for me. When I try using it I get an error:
![image](https://user-images.githubusercontent.com/9110528/120767998-68a3ec80-c524-11eb-9407-0e1928ce1487.png)

**Comment by xTEddie** [comment]
@asmailov I don't remember I ran into this issues. I'd recommend to uninstall all the ACS packages, then install them again and see if it works or not.

**Comment by xTEddie** [comment]
Installing `@azure/communication-chat` requires extra set up on React Native for me. 

- `npm install node-libs-react-native`
- Update *metro.config.js* to use React Native compatible Node Core modules
```ts
module.exports = {
  // ...
  resolver: {
    extraNodeModules: require('node-libs-react-native'),
  },
};
```
- Add `net` mock in *metro.config.js* to fix `net could not be found within the project`
```
module.exports = {
  // ...
  resolver: {
    extraNodeModules: {
      ...require('node-libs-react-native'),
      net: require.resolve('node-libs-react-native/mock/net') // Add mock
    }
};
```

- Add `tls` mock in *metro.config.js* to fix `tls could not be found within the project`
```
module.exports = {
  // ...
  resolver: {
    extraNodeModules: {
      ...require('node-libs-react-native'),
      net: require.resolve('node-libs-react-native/mock/net'),
      tls: require.resolve('node-libs-react-native/mock/tls') // Add mock
    }
};
```

- Import 'node-libs-react-native/globals' on top of your entry point file to fix `can't find variable Buffer`;
```
import 'node-libs-react-native/globals';
```

- Install `react-native-randomBytes` to fix `TypeError:null is not an object(evaluating 'RNRdandomBytes.seed')`
```
npm install react-native-randombytes --save 
```
