### ISSUE TITLE
IOS wkwebview support

### ISSUE THREAD

**Issue by sowsan** [Azure/Communication#214]
Does the web sdk support web rtc with IOS Wkwebview? Since IOS 14.3 onwards WKWebView support webrtc, I want to make sure that there are no SDK restrictions by checking the browser? Thanks!

**Comment by LeChrisS** [comment]
Bumping up this issue as I exactly encounter this problem with WKWebView and iOS 14.7 in a Cordova app.
I have successfully verified that WebRTC works with WKWebView by requesting the correct permissons.
However the Azure communication package errors out with a CallingCommunicationError: BrowserNotSupported message.
I do not see the rationale why this functionality is still blocked since WKWebView is able to do WebRTC now since a couple of months.
Thank you!

**Comment by LeChrisS** [comment]
Further digging into the issue I found that the SDK just checks the user agent and sees if the string "Safari" is present without actually further checking the WebRTC capabilities of the runtime present in memory.
If I modify the User Agent String that is being presented by the WKWebView the error is gone.
This seems like blocker for no actual reason.
Please have a look into this.
Thank you!
