### ISSUE TITLE
Protocol Documentation?

### ISSUE THREAD

**Issue by ganlbarone** [Azure/Communication#24]
Hello,
Is there anywhere to review the actual protocol documentation for this? Personally, I hate using libraries, and that is all I can find reference to in the material about this service.

Thanks much.

**Comment by ProbablePrime** [comment]
Hey @ganlbarone,

Thanks for your inquiry. I understand your ask and that you want to avoid using libraries and to potentially build your own, to your preferences.

Azure Communication Services has plans to release full REST API Documentation which closely matches REST documentation available for other Azure offerings. Using this documentation you should be able to talk directly to our services.

This documentation is currently on our team's plans but I am unable to share an exact timeline at this time. It is coming and when it does I'll reply back here to let you know what's happening.

In the meantime you can take a look at the REST Documentation for other Azure Features [here](https://docs.microsoft.com/rest/api/?view=Azure). This should give you a feel for what you can expect. Take a look and let me know if you have any additional questions.

In some areas of our documentation we do have some more advanced information which can give you an idea of some items that you might need to prepare in order to speak to our APIs directly. For example to use authentication with our services you'll need to sign the request following some instructions [here](https://docs.microsoft.com/azure/communication-services/concepts/authentication?#sign-an-http-request)

Please let me know if you have any other questions on this matter.

Thanks!

**Comment by ganlbarone** [comment]
Thanks for the update on this. Will await the rest docs. I am pretty familiar with Graph api and the other azure related apis so should be all set once this is released.

**Comment by ddematheu2** [comment]
REST API docs are published here: https://docs.microsoft.com/en-us/rest/api/communication/ let me know if this works to close the issue. @ganlbarone
