### ISSUE TITLE
Android: ACS shows status of call from CONNECTING to NONE always with both beta-9 and beta-8 version

### ISSUE THREAD

**Issue by ankiarora** [Azure/Communication#244]
**Describe the bug**
1. I followed the below link to Join my app to a team meeting. 
https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-teams-interop?pivots=platform-android
2. SDK version I used for ACS is 1.0.0-beta.9
3. When I Provide the teams link, and click on JOIN NOW button, The status shows CONNECTING and after a couple of seconds, it changes to NONE instead of showing IN LOBBY or CONNECTED.

**Steps to reproduce the behavior:**
1. Copy the same code for xml and activity as provided in documentation. 
https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-teams-interop?pivots=platform-android
2. Replace the accessToken with your access token.
3. Run the application.
4. Enter the teams URL you created
5. Click on Join Now button

**Expected behavior**
Status should change from CONNECTING to CONNECTED instead of NONE

**Screenshots**
![Screenshot_2021-04-01-21-29-10-605_com contoso acsquickstart](https://user-images.githubusercontent.com/19564143/113321632-6ad5a900-9331-11eb-825f-ea5cd80291df.jpg)

**Smartphone (please complete the following information):**
 - Device: Redmi K20
 - OS: Android 10

**Additional context**
2 weeks back, I tried the same piece of code, but with beta-8 version, and it was working fine. Now, it is neither working with beta-8 nor with beta-9.

**Logs**
Call Id: 8270bd00-ebfa-4a1b-a396-6ab50c02eeb6

**Comment by kagbakpem** [comment]
Hello @ankiarora,

Thanks for reporting this issue. From the looks of the internal telemetry, it seems like the connection was denied from the server side. This could be due to multiple factors, invalid token or interop unauthorized for the specific Teams tenant.
You mentioned you've tried this on 1.0.0-beta.8 and it was working? Can you confirm this is still the case?

**Comment by ankiarora** [comment]
Hello @kagbakpem,

Thank you for responding. 
It was working a couple of weeks back, but now it is **not** working with 1.0.0-beta.8.
So I tried with 1.0.0-beta.9 and still, it shows NONE message. Plus, I used the latest updated access token which was not expired.

**Comment by kagbakpem** [comment]
The issue is due to a restriction from our end that went into effect recently. So, please make sure to follow the documentation [here](https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-teams-interop?pivots=platform-android) and fill out the form [here](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR21ouQM6BHtHiripswZoZsdURDQ5SUNQTElKR0VZU0VUU1hMOTBBMVhESS4u) for this to be enable for your tenant and resource.

**Comment by mkambale** [comment]
@kagbakpem Does that mean if I have created a trail Azure account with my personal mail ID (say xyz@gmail.com), I will not be able to place request for teams interop scenario to be enabled and try ACS SDK before making purchase?

**Comment by kagbakpem** [comment]
@mkambale, Teams interop needs to be enabled for a specific tenant before the SDK allows you call the API. It's by design. The restriction was not being fully enforced previously but it is now in full effect. Please follow the steps highlighted in the documentation [here ](https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-teams-interop?pivots=platform-ios) and fill out the form [here ](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR21ouQM6BHtHiripswZoZsdURDQ5SUNQTElKR0VZU0VUU1hMOTBBMVhESS4u) for this to be enable for your tenant and resource.
