### ISSUE TITLE
Bring your own Carrier

### ISSUE THREAD

**Issue by InventiveLabs** [Azure/Communication#28]
Teams has Direct Routing through an SBC.

When will you be adding similar feature to ACS?

This will open up many more applications when you can integrate to outside carriers.

**Comment by svanvliet** [comment]
Yes, our plan is to offer a similar experience to Direct Routing for ACS. More details on our [blog here](https://azure.microsoft.com/en-us/blog/build-rich-communication-experiences-at-scale-with-azure-communication-services/). (I guess not more details, just a line in our roadmap 👍 )

**Comment by telecomsxchange** [comment]
> Yes, our plan is to offer a similar experience to Direct Routing for ACS. More details on our [blog here](https://azure.microsoft.com/en-us/blog/build-rich-communication-experiences-at-scale-with-azure-communication-services/). (I guess not more details, just a line in our roadmap 👍 )

@svanvliet what's the best way to be notified when BYOC becomes available ? We would love to be the best to test it our with our platform, we already have 300+ carrier interconnections, we can test across all pretty easily.

**Comment by NMuravlyannikov** [comment]
@telecomsxchange  we target early next year for this.

**Comment by boris-bazilevskiy** [comment]
@telecomsxchange please drop me an email with relevant contact info, we will let you know when we start onboarding

**Comment by InventiveLabs** [comment]
voiceelements.com has a multi-tenant software SBC that works with Teams currently.  We would also like notification, preview, or test when it becomes available.  Could you add voiceelements.com so I can send to acsfeedback.  Thanks.

**Comment by telecomsxchange** [comment]
> acsfeedback@microsoft.com

Done.

**Comment by telecomsxchange** [comment]
@boris-bazilevskiy I tried emailing, however we got an error that we're not an allowed sender. JFYI


`Your message couldn't be delivered to multiple recipients.
--
The groups only accept messages from people in their organization or on their allowed senders list, and your email address isn't on the lists.`

**Comment by boris-bazilevskiy** [comment]
please try again and put me in CC (boris.bazilevskiy@microsoft.com), we 'll check where the problem is

**Comment by telecomsxchange** [comment]
I think we have missed asking if BYOC will be for both Voice and SMS, am guessing protocols used will be SIP and SMPP, just want to reconfirm ?

**Comment by nmurav** [comment]
Good question @telecomsxchange  we will enable it for PSTN only. What is the scenario for SMS?

**Comment by telecomsxchange** [comment]
@nmurav just like voice, many enterprises have existing contracts / relationship with carriers. SMS/Texting is on the rise and businesses use it as much as PSTN calling, if not more in some scenarios. Two-way SMS, 2FA, promos campaigns etc... 

All CPaaS provider failed to provide perfect and consistent quality because they lack end to end control and don't have the resources to interconnect with every single operator in the world. BYOC should be for both voice and sms and even for DIDs. 

So if Azure voice or SMS routes failed to deliver the QoS expectation (due to carrier, routing etc..) the user has a choice of using his own carrier and not be stuck. Same with pricing, the user may get a much better deal price wise if they are domestically interconnected with operator. 

The freedom of carrier choice is a must in our experience and no user will be unhappy about that option. 

Hope it makes sense.

**Comment by VoxboneTGooch** [comment]
Have also sent a registration e mail for this when BYOC launches

**Comment by nmurav** [comment]
Makes sense, appreciate the reply. I added you on the waitlist of customers for the Direct Routing
