### ISSUE TITLE
Switch camera feature have a problem !

### ISSUE THREAD

**Issue by ozanurkn** [Azure/Communication#281]
hi,

When i did switch carema with below code. When i meeting with another person, my side changed camera but other person side  stopped the streaming as black page.

```
if (deviceManager.getCameras().size() >= 2) {
            if (desiredCamera.getCameraFacing().name().equals("FRONT")) {
                for (VideoDeviceInfo cameraInfoNew : deviceManager.getCameras()) {
                    if (cameraInfoNew.getCameraFacing().name().equals("BACK")) {
                        desiredCamera = cameraInfoNew;
                        break;
                    }
                }
            } else {
                for (VideoDeviceInfo cameraInfoNew : deviceManager.getCameras()) {
                    if (cameraInfoNew.getCameraFacing().name().equals("FRONT")) {
                        desiredCamera = cameraInfoNew;
                        break;
                    }
                }
            }
            try {
                if (getBinding().clPreMeetingScreen.getVisibility() == View.VISIBLE) {
                    previewVideoStream.switchSource(desiredCamera).get();
                } else if (getBinding().clCurrentMeetingScreen.getVisibility() == View.VISIBLE) {
                    currentVideoStream.switchSource(desiredCamera).get();
                }
            } catch (ExecutionException | InterruptedException e) {
                e.printStackTrace();
            }
}
```

i guess, after switch camera,it calls onRemoteVideoStreamsUpdated() method.

Can you help ?
thanks 
Ozan

**Comment by ozanurkn** [comment]
hi, my app features, it can close video stream, open video stream and switch camera back and front.

When i close video stream, calls onVideoStreamsUpdated() removedVideoStreams() method, When i open video stream , calls onVideoStreamsUpdated() addedVideoStreams() method, and when i switch camera , calls onVideoStreamUpdated() removedVideoStream() and addedVideoStreams() methods calling.

How can i detect where come from at removedVideStream() or addedVideoStream(), camera switch processing or close video streaming or open video streaming.

**Comment by jsaurezlee-msft** [comment]
This issue was resolved following these actions:

1. Logs from the the participant that switched the camera indicated that the camera switch was done correctly and the new camera started sending the new camera video to remote participants.
2. Remote participants got the onVideoStreamUpdated events with the old camera stream removed and the new one added. Closing the old stream and opening the new one renders the new camera frames.

As for @ozanurkn last question: There's no way to identify that a stream closed because of a camera switch or because the video was stopped from the source. Actually, a camera switch will disable the current stream and enable the new one (generating events to notify remote participants of a video stream change), treating it just like stopping and starting video from any camera.
