### ISSUE TITLE
ACS web calling connection state issue

### ISSUE THREAD

**Issue by syamkp1986** [Azure/Communication#328]
**Describe the bug**
I was trying to implement the azure ACS web feature in my angular application using angular redux.  It had been working fine while using the "@azure/communication-calling": "1.1.0-beta.2"  package. I had to update the version after deprecated the old version of the sdk. CallClient, Call Agent, join group, etc are working fine for me. After adding the call, it shows the ACS-related issue. The issue was happening after the below code execution.
```
addedCall.on('stateChanged', (): void => {
            dispatch(setCallState(addedCall.state));
          });
```

**To Reproduce**
1. Create Device Manager
2. Create Call Agent
3. Join to Group
4. Call added
5. After State Changing it shows the error. Please see the attached screenshot

![image](https://user-images.githubusercontent.com/19151969/124394233-3b617e80-dd1c-11eb-9103-8a32d192ee6b.png)
Please help me to figure it out.

**Comment by cwhil2492** [comment]
Hi @syamkp1986 do you have a repo so that we can clone your app and run it localy to try it out please? 

Can you also please repro and attach the full console log here? Use verbose log level: https://docs.microsoft.com/en-us/azure/communication-services/concepts/troubleshooting-info?tabs=csharp%2Cjavascript%2Cdotnet#enable-and-access-call-logs

**Comment by Grace-MacJones-MSFT** [comment]
Hi @syamkp1986, do you have any updates for us concerning this issue? Are you able to provide any information to the above questions?

**Comment by akania** [comment]
closing as we're not able to follow up, please reopen with requested information
