### ISSUE TITLE
ChatClient endpoint is ignored when CommunicationTokenCredentials created with other endpoint

### ISSUE THREAD

**Issue by janjouni** [Azure/Communication#377]
**Describe the bug**
We use the .net Communication Chat SDK in a Xamarin App and create the CommunicationTokenCredential through an API method on our webserver. If the webserver creates credentials with an existing CommunicationUserId and sends this back to the Xamarin app, the Xamarin app can create a ChatClient instance with another or a non existing endpoint. Nonetheless the ChatThreadClient created in the Xamarin app automatically connects to the endpoint the webserver created credentials for and is able to receive messages.

**To Reproduce**
1. Have a client app and a webserver component for handling handshake to communication service
2. Have an existing CommunicationService with existing users and threads in it 
3. Create credentials through the webserver API interface
4. Check everything is fine in the client app 
5. Change client app endpoint of ChatClient to a new communication service (or an non existing URI)
6. you will be still able to create the ChatClient instance along with the ChatThreadClient and get the messages as before

**Expected behavior**
I would expect to see an error on the client since the credentials are not eligible to connect to the new endpoint.
Or is this intended behaviour? From where does the SDK know to which endpoint it should connect then?

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur 11.5.2
 - Visual Studio for Mac 8.10
 - Xamarin Forms
 - Azure.Communication.Chat 1.0.1

**Comment by juancamilor** [comment]
Hi @janjouni 
Sorry for the delay. That behaviour is by design. The end point url just uses the domain part for the DNS lookup from the client side (i.e .communication.azure.com). Once our servers received the request, all the information required to route the request to the proper resource is driven by the security token. The security token is associated to just one resource,
so there is not any security risk of accessing a resource for which the token has not been issued. 
We will close this one for now but feel free to reopen it if you need further details.
Thanks !
