### ISSUE TITLE
There seems to be no call video or ability to have another caller join a particular call from the group call sample

### ISSUE THREAD

**Issue by xtianus79** [Azure/Communication#44]
**Describe the bug**
From the group call sample via the localhost, or deployed, there are 2 notable things. 

1. There is no video on the call and 
2. To whom am I calling or can there be a way to have 2 browser tabs to fulfill caller 1 and caller 2 to make it as if there are 2 callers on the call? 
3. Otherwise the people button at the top of the web client doesn't' show anything or any directory of people such as the people who belong to the tenant for a supposed user base to call.  Maybe I am thinking of this incorrectly. 
4. How do you add a person to the call?
5. How do you join a call to an already existing Teams call. I.e. Guest calling the call center. 

**To Reproduce**
1. Go to the web sample for the video call client demo
2. click start a call and nothing basically happens other than a url and a tool bar section at the top displays. 

**Expected behavior**

A video call with the ability for others to join or leave with ease.

**Screenshots**

**Desktop (please complete the following information):**
mac
chrome latestish

**Additional context**

**Comment by alex-kwan** [comment]
Hello. 

I was wondering if we could verify a few things so we can help you out :)

- Did you enable permissions for the use of your camera in this tab?
- I was wondering if you entered a value resource connection string into your appsettings.json?

(To add someone to a call)
To add someone. Once you in the group call, there is a join link at the bottom right hand corner of the side pane you can copy or just copy the URL and share it with someone. If the URL has a "groupId" then when someone else uses that link they will join your call.  
**If you are in localhost only tabs from your machine will be able to join that call. You will need to deploy to azure in order to other users from other devices to access your call.

(What is the defintion of a user?)
Every single "tab" is a newly minted "user". We don't ship a form of identity we just want to create a very simple communication experience allowing our partners to integrate communication into their systems which includes their own form of identity. Since we allow customers to bring their own identity, we created a basic identity for the purpose of demonstrating the communication features of our web SDK. If you would like to bring in concepts of your AAD login and tenant information I would encourage you to try out integrating the Graph APIs with this calling experience!

It definitely sounds like you are thinking of a whole teams experience. If you are interested a more teams centric example or even a call center. Please stay tuned it is something we are also interested in helping people build as well!

**Comment by xtianus79** [comment]
@alex-kwan So I have boiled it down to this sdk xhr request that is being blocked by my vpn 

post https://api3.cc.skype.com/conv

in relation to this call get 

https://euaz.turn.skype.com/relay


(failed)net::ERR_CONNECTION_RESET
--

**Comment by xtianus79** [comment]
@alex-kwan any update on this?

**Comment by alex-kwan** [comment]
@xtianus79  I believe the SDK is only available on a specific range of IPs that we are currently writing additional documentation for. As a potential work-around, are you able to test without using a VPN?

**Comment by RinaRish** [comment]
Hi @xtianus79 ! The document about supported API ranges is under construcrion. You should whitelist everything from this page https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#skype-for-business-online-and-microsoft-teams. Let me know if that helps

**Comment by xtianus79** [comment]
@RinaRish so we can focus in our requests are there particular endpoints and ip's that need to be whitelisted. Everything is a lot on this page for our environment.

**Comment by RinaRish** [comment]
Hi @xtianus79! I  just wanted to follow up and see if you were able to unblock yourself and make it work?
