### ISSUE TITLE
BackgroundBlurEffect.isSupported() returns true on unsupported browsers.

### ISSUE THREAD

**Issue by picorel** [Azure/Communication#535]
**Describe the bug; what happened?**

We want to check if blur background is supported and only show the video effect controls when it is supported. 

We followed the example from this [documentation](https://learn.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/video-effects) and added:

```
const backgroundBlurEffect = new BackgroundBlurEffect(); 
const backgroundBlurSupported = await backgroundBlurEffect.isSupported(); 
```

`isSupported` is returning `true` in some unsupported browsers. We noticed it in Firefox (Desktop on MacOS) and some mobile devices (Chrome on Android and sometimes on iOS). 

Is it expected or a known issue? 

If we try to enable the video effect in these browsers, it doesn't work. We are using the `CallComposite`, so if we try to blur the background `callAdapter.startVideoBackgroundEffect({...})`, it shows the message `"Unable to apply video effect."`.

**In what environment did you see the issue?**

We are currently using 
- "@azure/communication-react": "1.7.0-beta.2",
- "@azure/communication-calling": "1.15.1-beta.1",
- "@azure/communication-calling-effects": "1.0.0-beta.2",
- "@azure/communication-chat": "1.3.2-beta.3",

We also tried with "@azure/communication-calling-effects": “1.0.1” and "@azure/communication-calling": "1.16.3" and `isSupported` also returns `true`. 

- OS & Device: MacOS
- Browser: Mozilla Firefox 117.0

**Comment by gaobob-msft** [comment]
@akania

**Comment by pkestikar** [comment]
Hi @picorel, thanks for reporting the issue. We'll aim to fix this in our upcoming beta release of the SDK.

**Comment by pkestikar** [comment]
Hi @picorel , so background blur should work in Firefox Desktop MacOS so isSupported returning `true` there is valid.
Though, `isSupported` returning true on mobile devices is a bug - we don't support background blur/replacement on mobile devices yet.
This should be fixed in our new beta - https://www.npmjs.com/package/@azure/communication-calling/v/1.20.1-beta.2 

The `isSupported` on the effect instance (`BackgroundBlurEffect` for eg) is now deprecated. There is a new `isSupported` method on the `VideoEffectsFeature` API now, that will return a more accurate check. Please try it out and let us know how it fares.
