### ISSUE TITLE
iOS: dispose on ACSRenderer and ACSRendererView

### ISSUE THREAD

**Issue by terrychen1122** [Azure/Communication#62]
Hi, I realized both ACSRenderer and ACSRendererView have a method `dispose`. Since it doesn't have doc, when are we supposed to call this method?

**Comment by mariusu-msft** [comment]
API Reference Docs can be found here https://docs.microsoft.com/en-us/objectivec/communication-services/calling/acsrenderer but it seems we are missing documentation for this method.

@RinaRish can you track this please?

@sankum-msft what is the guidance for dispose method? Can you please update https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/calling-client-samples?pivots=platform-ios with guidance on when the method should be called?

**Comment by sankum-msft** [comment]
Video rendering is a resource intensive task, these methods allow you to clean up resources when you don't need to render a video anymore. Having `dispose()` on both renderer and view objects will allow renderer in future to manage multiple views.

For now, when you stop renderering a video stream(incoming or preview), please call `dispose()` on the corresponding `ACSRenderer` object after removing the view from UI. `ACSRenderer.dispose()` invokes `ACSRendererView.dispose()` internally.

**Comment by terrychen1122** [comment]
Sorry, a few more questions:
1. Are we supposed to strongly hold a reference of `ACSRenderer`? If so, when we call its `dispose()`, and for the next time we want a view, am I supposed to call `createView` again? or should we create a new renderer

2. How about when a view controller that contains `ACSRendererView` in its hierarchy is dismissed by the user? Does the library auto `dispose` them (renderer view and renderer) when they are getting deallocated? If not, I think it would be hard to rely on the consumers to do it.

**Comment by sankum-msft** [comment]
1. Yes, you would need strong reference of `ACSRenderer` to dispose it off properly otherwise you will end up with memory leak. `ACSRenderer` is useless once it is disposed and you can let the object get garbage collected at that point. You should create a new renderer if you decide to render a stream after disposing the original renderer.
2. No, you don't need to keep `ACSRenderer` around once it is disposed.
3. It is app's responsibility to dispose renderer (which will dispose all related views as well) when it doesn't want to render the video. We will have auto disposal for both `ACSRenderer` and `ACSRendererView` in future but for now, we let the app decide when they should be cleaned up.

**Comment by mariusu-msft** [comment]
@sankum-msft It may be helpful for later to have a good lifetime diagram of the renderer and what we expect to happen in various app lifecycle states

**Comment by terrychen1122** [comment]
@sankum-msft Gotcha. I think all of these should be documented since it's very important for us to make sure we use the library properly otherwise I don't know it would cause memory leak. For #3, I think the only way I can ensure ACSRenderer and the view get properly disposed in all scenarios is to have a wrapper for `ACSRenderer` and dispose it in `dealloc`.
