### ISSUE TITLE
Video freezing after a few seconds

### ISSUE THREAD

**Issue by JaKoBowden** [Azure/Communication#73]
I've set up a group video call in my own web application but after a few seconds I see JS.TsCalling.SignalingAgent shows "received status 498, stop subscribing" As soon as that message appears in the chrome console, the remote video stream freezes.
I've tried replicating in the 'hero' calling app, but it doesn't exhibit this behavior. As the documentation doesn't contain much in the way of error codes, I assume I'm missing something in the way I'm standing up the call, but I can't see where I'm going wrong when I compare my code to the sample. I think a more moderate example, somewhere between the quickstart, and the 'hero' example (for those of us that don't use react/redux) would be extremely beneficial.

**Comment by RinaRish** [comment]
Hi @JaKoBowden! Thanks for your feedback. We are working on our error code documentation but meanwhile, @akania or @chriswhilar will look into the error and get back to you.

**Comment by akania** [comment]
Hi @JaKoBowden , can you repro consistently?
if so ,can you please share a call id, you can read it by accessing 
```js
call.id 
```
property
https://docs.microsoft.com/en-us/javascript/api/azure-communication-services/@azure/communication-calling/call?view=azure-communication-services-js#id
In addition if you can provide a full console output and attach to this ticket - that will help us to troubleshoot it.

Based on the description, it looks like your endpoint may be having connectivity issues, possibly related to network configuration

**Comment by JaKoBowden** [comment]
Hi @akania, I'll get the call.id shortly and the console output, but the assumption about the issue related to network configuration is incorrect, as the calling/hero example works on the same endpoint without any freezing issues.

**Comment by JaKoBowden** [comment]
Hi @akania Turns out if you join a group call with a call option where the local stream is specified like so:
`const placeCallOptions = { videoOptions: { localVideoStreams: [localCameraStream] } };
const context = { groupId: "7a4b034e-dfc8-44da-9eb8-69bdcd9ad8ce" };
call = await callAgent.join(context, placeCallOptions);`
the video will freeze at the other end after 15-30 seconds or so.
However, if you join the call without specifying the local video stream and then later start the video on the call like so:
`await call.startVideo(localCameraStream);`
the video will not ever freeze. I don't know if this is a bug in the callAgent.join function or if this is intended behavior?

**Comment by akania** [comment]
@JaKoBowden this indeed sounds like a bug - can you please gather full console output from both scenarios ( join with video, join -> add video ) and attach to this ticket - we'll investigate based on that.

**Comment by chriswhilar** [comment]
Hey @JaKoBowden can you please repro and provide us the logs?

Also, how are you testing this out? Are you doing everything on one machine locally so that the same physical camera is being used accross the different browsers you have opened on this 1 machine?



I did some investigation on my side and i noticed the following with these 2 scenarios below:

**Scenario 1:** The video freezing is only happening for me when i do everything in 1 machine. So from this machine i have 3 browsers opened and they are all going to use the same physical camera. All 3 browsers join the same group call so there are a total of 3 participants in the group call. Then I get alot of video freezes.

**Scenario 2:** Now if i try this same scenario but from 3 different machines. So each machine has 1 browser opened and each machine uses its own physical camera. Each browser from each machine join the same group call so there are a total of 3 participants in the group call. Then there are NO video freezes at all.

Could you please try out scenario 2? Id like to see if the video freezing goes away for you in this case.
