### ISSUE TITLE
Web: Guidance for releasing/reusing resources after call finished

### ISSUE THREAD

**Issue by eliaspuurunen** [Azure/Communication#76]
**Is your feature request related to a problem? Please describe.**
Currently the documentation is sparse re:
- how to properly release resources when a call is finished.
- which resource types are long-lived (app lifetime) vs. short-lived (call lifetime)

For instance, in our app we allow people to hop between calls. They may spend 5 minutes on call 1, leave that call, spent 5 minutes off a call, then 5 minutes on call 2.

Our app stays active the whole time.

We are not sure which resources should be long-lived (e.g. the Call Agent, Device Manager) and which should be short-lived. One potential issue we see is that depending on which resources are long-lived may determine when the "microphone/camera is active" indicator is lit in the user agent.

Ideally when not on a call, that indicator would be off (i.e. we're not using their camera/mic at all unless on call).

**Comment by akania** [comment]
Hi @eliaspuurunen, let me answer in order

1) how to properly release resources when a call is finished:
When call is finished our SDK will terminate signaling&media sessions leaving you with an instance of the call that holds the last state of it, so you can check callEndReason etc.., if your app won't hold the reference to the Call instance - JavaScript GC will clean up everything so in terms of memory consumption your app should go back to initial state from before the call.

2) which resource types are long-lived (app lifetime) vs. short-lived (call lifetime):
 in terms of resources types that are long-lived, 
* CallClient
* CallAgent
* DeviceManager
are all considered to be "long-lived" - you can create them and keep referenced for a long time, they are very light in terms of resource(memory) consumption so won't impact perf.

Short-lived resources are the ones that are playing some role in the call itself, or are interacting with local media devices, so e.g:
* Call instance - since it's the one holding the actual state of the call ( both signaling and media )
* Renderer with it's RendererViews - handling video rendering
These will consume more cpu&memory, but once call ends - SDK will cleanup all the state and release resource.

`For instance, in our app we allow people to hop between calls. They may spend 5 minutes on call 1, leave that call, spent 5 minutes off a call, then 5 minutes on call 2.`
Here depending if you end the initial call, or if you put it on hold and switch to another call - resource consumption will increase with number of active calls ( including ones that are on hold )

`One potential issue we see is that depending on which resources are long-lived may determine when the "microphone/camera is active" indicator is lit in the user agent. Ideally when not on a call, that indicator would be off (i.e. we're not using their camera/mic at all unless on call).`
This sounds like a bug - can you please share exact repro steps? Camera indicator shouldn't be active unless you're actively previewing ( so having a Renderer-> view created from local camera device ) or sending video from your camera in the call - can you confirm that it's not the case please.

**Comment by eliaspuurunen** [comment]
This is fantastic clarification, thank you!

Re: mic/camera active indicator - we narrowed down the issue. It was due to a workaround we put in place for issue #46. 

Re: short/long lived - this would be amazing to have in the docs. What's clear from docs and samples is how to start a call. What is fuzzy is switching/leaving/starting new calls (i.e. after hello world). 

Thank you!

**Comment by akania** [comment]
Thank you @eliaspuurunen , it's a really valuable feedback , we'll update our documentation.

**Comment by tophpalmer** [comment]
AB#2284971

**Comment by mariusu-msft** [comment]
Closing. This has been addressed in documentation.

**Comment by akania** [comment]
[Link to documentation](https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/calling-client-samples?pivots=platform-web#releasing-resources)
