### ISSUE TITLE
[iOS] takes 30+ seconds to get the remote participant update to come through when a participant kills their app

### ISSUE THREAD

**Issue by terrychen1122** [Azure/Communication#89]
As the title suggests, is this a technical limitation that it gets this long? is there something we can improve here to reduce this time and make the experience more responsive and instant?

**Comment by mariusu-msft** [comment]
The duration you are seeing is how long it takes for all timeouts to expire and endpoint being forced out of the call.
This includes the time we allow the endpoint to recover from intermittent connection issues.

Due to retry strategies, allowing reconnect attempts and timeouts this cannot be instant.

I'm making this as a documentation issue, to better document the behavior.

**Comment by tophpalmer** [comment]
AB#2309708

**Comment by RinaRish** [comment]
Yes this is a limitation, we have documented it here - https://docs.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/calling-sdk-features#calling-sdk-timeouts
